import type { Post, Notification } from "@/types";

export const FEED_DATA: Post[] = [
  {
    id: 9,
    user: "shizuru", initial: "S",
    item: "ブルーボトルコーヒー インスタントコーヒーセット（ブライト・エスプレッソ）",
    relation: "先生・恩師", scene: "誕生日", price: "〜3,000円",
    about: "出張が多くて、宿泊先の部屋にコーヒーメーカーがあって朝コーヒー飲めるのが嬉しいってSNSに書いてた",
    reason: "旅先にサクッと持っていけるインスタントにしようとすぐ決まった。かさばらないし、ブルーボトルなら間違いないと思って即決",
    reaction: "たまたまお誕生日当日にお会いするタイミングがあって、その場でお渡しできた",
    likes: 0, date: "4月",
    url: "https://store.bluebottlecoffee.jp/products/s346",
  },
  {
    id: 10,
    user: "shizuru", initial: "S",
    item: "メゾン マルジェラ「レプリカ」フレグランス ディスカバリーコレクション",
    relation: "友達", scene: "誕生日", price: "〜5,000円",
    about: "いつもハードワークで忙しそうな子。昔一緒に香水屋さんに寄ったとき、仕事で辛くなった時に気持ちを切り替えるために香りを使うって話してくれた",
    reason: "普段からつけるわけじゃないけど、スイッチを切り替えるために香りを使うって言ってたのが頭に残ってた。ディスカバリーセットなら色んな香りを試せるから、気分で使い分けられると思って",
    reaction: undefined,
    likes: 0, date: "3月",
    url: "https://mall.line.me/sb/maisonmargiela/7723390",
  },
  {
    id: 11,
    user: "shizuru", initial: "S",
    item: "「立町カヌレ」カヌレギフトセット（15個入り）",
    relation: "友達", scene: "なんでもない日", price: "〜5,000円",
    about: "カヌレが大好きな子。同棲してて、うちに来てくれた時に私の大好きなピエールエルメをてんこ盛り買ってきてくれた",
    reason: "カヌレが好きって知ってたからてんこ盛りの詰め合わせに。ピエールエルメの時の嬉しさを今度は私から返したかった。同棲してるから基本シェアになるけど、その子自身のためのものにしたかった",
    reaction: undefined,
    likes: 0, date: "4月",
    url: "https://www.castagna.co.jp/pasticceria/cannelegiftset/",
  },
  {
    id: 12,
    user: "shizuru", initial: "S",
    item: "TEAPOND ポーチ入り ティータイムセット",
    relation: "友達", scene: "送別", price: "〜3,000円",
    about: "紅茶屋さんでバイトするくらい紅茶好きな子。家の近くにteapondがあってよく一緒に遊びに来てくれてた",
    reason: "この子に贈るならここしかないと思った。引越し後はまだ落ち着かないだろうからティーバッグで手軽に飲めるのも考えた。ポーチ付きでグッズとしても使えるのも決め手",
    reaction: "新居で紅茶を飲む時にふと思い出してくれたらいいな",
    likes: 0, date: "4月",
    url: "https://teapond.jp/collections/gift/products/tts0003",
  },
  {
    id: 13,
    user: "shizuru", initial: "S",
    item: "TAKIBI BAKERY クリスマスシュトーレン ＋ 旅する紅茶 ＋ 小花束",
    relation: "先生・恩師", scene: "送別", price: "〜5,000円",
    about: "コーヒー屋さんで、もうすぐご結婚されると聞いていた。長くお世話になった方",
    reason: "コーヒーのプロだから、逆に普段選ばない紅茶を贈りたかった。シュトーレンはクリスマスの時期でもあったし、パートナーと一緒に食べてほしくて。お花は主役じゃなくていい、ありがとうを伝える1本として添えた",
    reaction: undefined,
    likes: 0, date: "12月",
    url: "https://csonline.cifaka.jp/?pid=64257741",
  },
];

export const NOTIFICATIONS: Notification[] = [
  { id: 1, type: "like", user: "yuki_chan", initial: "Y", text: "いいねしました", sub: "メゾン マルジェラ「レプリカ」フレグランス ディスカバリーコレクション", time: "さっき", unread: true },
  { id: 2, type: "like", user: "haru_okuri", initial: "H", text: "いいねしました", sub: "TAKIBI BAKERY クリスマスシュトーレン ＋ 旅する紅茶 ＋ 小花束", time: "12分前", unread: true },
  { id: 3, type: "like", user: "momo_gift", initial: "M", text: "いいねしました", sub: "「立町カヌレ」カヌレギフトセット（15個入り）", time: "1時間前", unread: true },
  { id: 4, type: "follow", user: "nana_present", initial: "N", text: "フォローしました", sub: "", time: "3時間前", unread: false },
  { id: 5, type: "like", user: "sora_memo", initial: "S", text: "いいねしました", sub: "ブルーボトルコーヒー インスタントコーヒーセット（ブライト・エスプレッソ）", time: "昨日", unread: false },
  { id: 6, type: "like", user: "rio_gift", initial: "R", text: "いいねしました", sub: "TEAPOND ポーチ入り ティータイムセット", time: "昨日", unread: false },
  { id: 7, type: "follow", user: "kana_log", initial: "K", text: "フォローしました", sub: "", time: "2日前", unread: false },
];
