import type { Post, Notification } from "@/types";

export const FEED_DATA: Post[] = [
  {
    id: 14,
    user: "Katsuya", initial: "K",
    item: "お猪口",
    relation: "友達", scene: "手土産", price: "〜3,000円",
    about: "大学の同期。二十歳になったばかり。",
    reason: "陶器市で素敵なお猪口を発見。お互いに二十歳になってお酒が飲めるようになったので、一緒に飲みたいという気持ちを込めて。",
    reaction: "素直に喜んでくれた。仲良いグループみんなにあげたので、一体感みたいなのがより強くなった気がした。",
    likes: 0, date: "5月",
    persona: ["お酒好き", "同期", "グループ"],
    vibes: ["一緒に楽しめるものがよかった", "一体感が生まれそう", "この出会いを形にしたかった"],
  },
  {
    id: 15,
    user: "WAEI", initial: "W",
    item: "メイソンピアソン ヘアブラシ",
    relation: "恋人", scene: "記念日", price: "それ以上",
    about: "100均のものでも壊れるまで長く使う人",
    reason: "ほかの有名プロダクトはあったけど、「長く使う人」にずっとついて行ってくれるだろうプロダクトはこのブランドだけだった。髪を梳かすときは相手の後頭部で顔は見えないけど、自分があげたブラシが見えるならとても良い時間になるなとも思ったから。",
    reaction: "突然突撃してケーキと一緒にあげて喜んでくれた！",
    likes: 0, date: "12月",
    url: "https://www.masonpearson.jp/",
    persona: ["ものを大切にする", "長く使う", "丁寧な暮らし"],
    vibes: ["ずっと使い続けてほしい", "毎日の時間に自分がいてほしい", "ちゃんと見てたことが伝わる"],
  },
  {
    id: 9,
    user: "shizuru", initial: "S",
    item: "ブルーボトルコーヒー インスタントコーヒーセット（ブライト・エスプレッソ）",
    relation: "先生・恩師", scene: "誕生日", price: "〜3,000円",
    about: "出張が多くて、宿泊先の部屋にコーヒーメーカーがあって朝コーヒー飲めるのが嬉しいってSNSに書いてた",
    reason: "旅先にサクッと持っていけるインスタントにしようとすぐ決まった。かさばらないし、ブルーボトルなら間違いないと思って即決",
    reaction: "たまたまお誕生日当日にお会いするタイミングがあって、その場でお渡しできた",
    likes: 0, date: "4月",
    url: "https://store.bluebottlecoffee.jp/products/s346",
    persona: ["コーヒー好き", "カフェ好き", "出張多い", "ハードワーカー"],
    vibes: ["旅先でふと思い出してほしい", "さりげなく気遣いが伝わる", "その人の日常に自然と馴染む"],
  },
  {
    id: 10,
    user: "shizuru", initial: "S",
    item: "メゾン マルジェラ「レプリカ」フレグランス ディスカバリーコレクション",
    relation: "友達", scene: "誕生日", price: "〜5,000円",
    about: "いつもハードワークで忙しそうな子。昔一緒に香水屋さんに寄ったとき、仕事で辛くなった時に気持ちを切り替えるために香りを使うって話してくれた",
    reason: "普段からつけるわけじゃないけど、スイッチを切り替えるために香りを使うって言ってたのが頭に残ってた。ディスカバリーセットなら色んな香りを試せるから、気分で使い分けられると思って",
    reaction: undefined,
    likes: 0, date: "3月",
    url: "https://mall.line.me/sb/maisonmargiela/7723390",
    persona: ["おしゃれ好き", "センスいい", "香り好き", "ハードワーカー", "忙しそう"],
    vibes: ["辛い時にそっとそばにいてあげられる", "ちゃんと聞いてたよが伝わる", "気分の切り替えに使ってほしい"],
  },
  {
    id: 11,
    user: "shizuru", initial: "S",
    item: "「立町カヌレ」カヌレギフトセット（15個入り）",
    relation: "友達", scene: "なんでもない日", price: "〜5,000円",
    about: "カヌレが大好きな子。同棲してて、うちに来てくれた時に私の大好きなピエールエルメをてんこ盛り買ってきてくれた",
    reason: "カヌレが好きって知ってたからてんこ盛りの詰め合わせに。ピエールエルメの時の嬉しさを今度は私から返したかった。同棲してるから基本シェアになるけど、その子自身のためのものにしたかった",
    reaction: undefined,
    likes: 0, date: "4月",
    url: "https://www.castagna.co.jp/pasticceria/cannelegiftset/",
    persona: ["甘いもの好き", "食いしん坊", "グルメ好き"],
    vibes: ["その子自身のためのものにしたかった", "嬉しさをお返ししたかった", "贈った後の顔が浮かんだ"],
  },
  {
    id: 12,
    user: "shizuru", initial: "S",
    item: "TEAPOND ポーチ入り ティータイムセット",
    relation: "友達", scene: "送別", price: "〜3,000円",
    about: "紅茶屋さんでバイトするくらい紅茶好きな子。家の近くにteapondがあってよく一緒に遊びに来てくれてた",
    reason: "この子に贈るならここしかないと思った。引越し後はまだ落ち着かないだろうからティーバッグで手軽に飲めるのも考えた。ポーチ付きでグッズとしても使えるのも決め手",
    reaction: "新居で紅茶を飲む時にふと思い出してくれたらいいな",
    likes: 0, date: "4月",
    url: "https://teapond.jp/collections/gift/products/tts0003",
    persona: ["紅茶好き", "カフェ好き", "インドア派", "おうち時間好き"],
    vibes: ["新居でふと思い出してほしい", "この場所の記憶を持って行ってほしい", "落ち着いた時間に使ってほしい"],
  },
  {
    id: 13,
    user: "shizuru", initial: "S",
    item: "TAKIBI BAKERY クリスマスシュトーレン ＋ 旅する紅茶 ＋ 小花束",
    relation: "先生・恩師", scene: "送別", price: "〜5,000円",
    about: "コーヒー屋さんで、もうすぐご結婚されると聞いていた。長くお世話になった方",
    reason: "コーヒーのプロだから、逆に普段選ばない紅茶を贈りたかった。シュトーレンはクリスマスの時期でもあったし、パートナーと一緒に食べてほしくて。お花は主役じゃなくていい、ありがとうを伝える1本として添えた",
    reaction: undefined,
    likes: 0, date: "12月",
    url: "https://csonline.cifaka.jp/?pid=64257741",
    persona: ["コーヒー好き", "甘いもの好き", "グルメ好き", "ハードワーカー", "花が好き"],
    vibes: ["プロだからこそ逆張りしたかった", "ふたりで楽しんでほしかった", "ありがとうをそっと添えたい"],
  },
  {
    id: 16,
    user: "JURI", initial: "J",
    item: "ADDICTION リップスティック",
    relation: "友達", scene: "誕生日", price: "〜5,000円",
    about: "あんまり化粧品を買うイメージはないけど化粧をしないわけじゃなくて、赤いリップが似合いそうな子",
    reason: "誕生日ならデパコスがいいかなーって思って、名前やこれまでの印象と色だけじゃなくてその商品の名前が素敵なものを選びたかった。SUQQUと悩んだけど、アディクションの鮮やかさやネーミングセンスの方がぴったりだなぁと思ったので選んだ",
    reaction: "あげたのはもう数年前だけどとっても気に入ってくれて自分で2本目も買ってた",
    likes: 0, date: "誕生日",
    url: "https://www.addiction-beauty.com/site/g/gMAPJ001/",
    persona: ["おしゃれ", "ナチュラルメイク", "色が似合う", "美意識ある"],
    vibes: ["名前まで含めてその人にぴったりを選びたかった", "何年後も使い続けてほしい", "センスが伝わるものがよかった"],
  },
];

export const NOTIFICATIONS: Notification[] = [
  { id: 1, type: "like", user: "yuki_chan", initial: "Y", text: "いいねしました", sub: "メゾン マルジェラ「レプリカ」フレグランス ディスカバリーコレクション", time: "さっき", unread: true },
  { id: 2, type: "like", user: "haru_okuri", initial: "H", text: "いいねしました", sub: "TAKIBI BAKERY クリスマスシュトーレン ＋ 旅する紅茶 ＋ 小花束", time: "12分前", unread: true },
  { id: 3, type: "like", user: "momo_gift", initial: "M", text: "いいねしました", sub: "「立町カヌレ」カヌレギフトセット（15個入り）", time: "1時間前", unread: true },
  { id: 4, type: "follow", user: "nana_present", initial: "N", text: "フォローしました", sub: "", time: "3時間前", unread: false },
  { id: 5, type: "like", user: "sora_memo", initial: "S", text: "いいねしました", sub: "ブルーボトルコーヒー インスタントコーヒーセット（ブライト・エスプレッソ）", time: "昨日", unread: false },
  { id: 6, type: "like", user: "rio_gift", initial: "R", text: "いいねしました", sub: "TEAPOND ポーチ入り ティータイムセット", time: "昨日", unread: false },
  { id: 7, type: "follow", user: "kana_log", initial: "K", text: "フォローしました", sub: "", time: "2日前", unread: false },
];
